### PR TITLE
docs: use quantinuum-sphinx theme [OLD]

### PR DESCRIPTION
**Pull request by CalMacCQ**
OLD (See #108)

### CODE REVIEW

**Comment by daniel-mills-cqc** [comment]
Could you make `develop` the target of this PR? I see the CI is having a problem with `types-pkg-resources`. I think this should be fixed by the newer version of pytket which develop should be using.

**Comment by CalMacCQ** [comment]
Seems I get a lot of merge conflicts from changing the base branch

Screenshot 2024-10-02 at 10 26 48

**Comment by CalMacCQ** [comment]
> Could you make `develop` the target of this PR? I see the CI is having a problem with `types-pkg-resources`. I think this should be fixed by the newer version of pytket which develop should be using.



> Could you make `develop` the target of this PR? I see the CI is having a problem with `types-pkg-resources`. I think this should be fixed by the newer version of pytket which develop should be using.

Seems I get a lot of merge conflicts from changing the base branch

Screenshot 2024-10-02 at 10 26 48

**Comment by daniel-mills-cqc** [comment]
> > Could you make `develop` the target of this PR? I see the CI is having a problem with `types-pkg-resources`. I think this should be fixed by the newer version of pytket which develop should be using.
> 
> Seems I get a lot of merge conflicts from changing the base branch
> 
> Screenshot 2024-10-02 at 10 26 48

I think those are coming from existing differences between `main` and `develop`, rather than anything that you have changes. What would be the easiest way to address this? Could you make the changes in a branch of of `develop`?

**Comment by CalMacCQ** [comment]
> I think those are coming from existing differences between `main` and `develop`, rather than anything that you have changes. What would be the easiest way to address this? Could you make the changes in a branch of of `develop`?

Ah yes I can give that a shot

**Comment by CalMacCQ** [comment]
> I think those are coming from existing differences between `main` and `develop`, rather than anything that you have changes. What would be the easiest way to address this? Could you make the changes in a branch of of `develop`?

See #108

**Pull request closed without merging**
