### PR TITLE
Update docstrings for gen_CDR_MitEx

### PR DESCRIPTION
**Pull request by sjdilkes**
Docs has incorrect strings for gen_CDR_MitEx kwargs for generating combined schemes.

### CODE REVIEW

**Comment by daniel-mills-cqc** [comment]
This PR should be into develop? I take it that the last commit is the relevant one?

**Comment by sjdilkes** [comment]
> This PR should be into develop? I take it that the last commit is the relevant one?

I want the changes to be made immediately to the docs so it needs to be into main.

I'm not sure whats up with the commit history, I'll have a look. But yeah just the last commit.

**Comment by sjdilkes** [comment]
> This PR should be into develop? I take it that the last commit is the relevant one?

The number of commits is just to do with my local version of main being funny.

**Comment by sjdilkes** [comment]
> > This PR should be into develop? I take it that the last commit is the relevant one?
> 
> The number of commits is just to do with my local version of main being funny.



> This PR should be into develop? I take it that the last commit is the relevant one?

If you would prefer I am happy to reopen the PR to develop and then merge from develop into main.

**Pull request closed without merging**
