### PR TITLE
docs: use quantinuum-sphinx theme

### LINKED ISSUE #106: Use quantinuum-sphinx documentation theme

### PR DESCRIPTION
**Pull request by CalMacCQ**
Closes #106 

Note that I've merged the manual and API docs into a single sphinx build.

Local build screenshot below

Screenshot 2024-10-01 at 23 10 24

### CODE REVIEW

**Comment by CalMacCQ** [comment]
docs build now passes on C.I.

Would you rather I added all the docs dependencies to `pyproject.toml` under a `docs` grouping or something?

**Comment by daniel-mills-cqc** [comment]
I see that some unrelated tests are failing. These have been repaired now. If you rebase onto develop then these tests should pass.

**Comment by daniel-mills-cqc** [comment]
We have also moved to using the main branch as the default branch now. Hopefully it won't be a problem to change the target once you have rebased but let's see.

**Comment by daniel-mills-cqc** [comment]
This is all looking good. We'd just need to change the target to main. Is that straightforward?

**Comment by CalMacCQ** [comment]
> This is all looking good. We'd just need to change the target to main. Is that straightforward?

oof big diff with some conlficts when I change the base branch
Screenshot 2024-11-20 at 16 51 36

**Comment by daniel-mills-cqc** [comment]
Superseded by -> https://github.com/CQCL/Qermit/pull/120

**Pull request closed without merging**
