### PR TITLE
Docs/update theme

### PR DESCRIPTION
**Pull request by CalMacCQ**
Updated docs theme to `sphinx_book_theme~=1.0.1`

Also done the same for the manual.

Theres some CI nastiness as I had to change the base branch to develop from main. Let me know if you want me to just make a fresh PR.

### CODE REVIEW

**Comment by CalMacCQ** [comment]
@sjdilkes what do you think I should do about the `0.4.0` commit?

**Comment by sjdilkes** [comment]
> @sjdilkes what do you think I should do about the `0.4.0` commit?

I believe @daniel-mills-cqc is going to take a look at https://github.com/CQCL/Qermit/pull/81 and fix the issues. I think we're good to leave this PR open for now and pick it up again once that fix is made.

**Comment by daniel-mills-cqc** [comment]
You should be able to continue working on this now that https://github.com/CQCL/Qermit/pull/82 is in. Rebasing on develop should get the tests passing.

https://github.com/CQCL/Qermit/pull/89 is also relevant but doesn't need to go in first.

A couple of things:
- Would it be possible to clear up the git history a little, just to clarify what has changed?
- Have these changes also been applied to the manual or just the docs?

**Comment by CalMacCQ** [comment]
Giving that this docs theme change is a 5-10 minute job - would it be alright to just make a fresh PR (branching off develop) making this change rather than trying to tidy up this messy PR?

**Pull request closed without merging**
