### PR TITLE
update pytket

### PR DESCRIPTION
**Pull request by cqc-melf**
this will allow newer versions of pytket to be used now and in the future.

### CODE REVIEW

**Comment by cqc-melf** [comment]
Not sure what your workflow for release is, would be nice if this could be released soon.

**Comment by daniel-mills-cqc** [comment]
Thanks @cqc-melf! As a small comment would you mind using develop as the target of this PR?

**Comment by cqc-melf** [comment]
> I'm not quite sure why the mac tests should be failing with the newer version of pytket, but it should fine to case things as mypy recommends.

Has there been a new mypy release in that time? Do you use a fixed version?

**Comment by daniel-mills-cqc** [comment]
I also note that `tests/test_requirements.txt` specifies `pytket~=1.0.1` which should probably also be changed. I think in-fact it might be better to remove pytket from the test requirements to avoid conflicts there?

**Comment by daniel-mills-cqc** [comment]
> > I'm not quite sure why the mac tests should be failing with the newer version of pytket, but it should fine to case things as mypy recommends.
> 
> Has there been a new mypy release in that time? Do you use a fixed version?

The version should be fixed to 0.901, which is not the latest version of mypy in any case :/

**Comment by daniel-mills-cqc** [comment]
Seems like a whole new set of errors. @sjdilkes, do you know what recent pytket changes could cause these tests to fail? My apologies, I'm not terribly familiar with the parts of the code where the tests are failing 😬 .

**Comment by sjdilkes** [comment]
> Seems like a whole new set of errors. @sjdilkes, do you know what recent pytket changes could cause these tests to fail? My apologies, I'm not terribly familiar with the parts of the code where the tests are failing 😬 .

How unexpected! No obvious idea, I will have a look today though. Maybe something to do with `Transform.RebaseToCliffordSingles` as that method is common to both, but still confusing.

**Review by sjdilkes — APPROVED** [review]

**Pull request merged**
